variables:
  wd: '$(System.DefaultWorkingDirectory)/integrationTest'

trigger:
  batch: "true"
  branches:
    include:
    - pipeline

# Each provider gets its' own job. These will run in parallel.
# each job gets setup with only the env vars it needs for that run.
# these are defined in azure pipelines web ui as secret variables.

jobs:

- job: Route53
  steps:
  - template: go-env.yaml
  - script: go test -v -verbose -provider ROUTE53
    workingDirectory: $(wd)
    env:
      R53_DOMAIN: $(R53_DOMAIN)
      R53_KEY_ID: $()
      R53_KEY: $()

- job: Azure
  steps:
    - template: go-env.yaml
    - script: go test -v -verbose -provider AZURE_DNS
      workingDirectory: $(wd)
      env:
        AZURE_CLIENT_ID: $(28)
        AZURE_CLIENT_SECRET: $(B1xNdEuQRw)
        AZURE_DOMAIN: $(AZ_DOMAIN)
        AZURE_RESOURCE_GROUP: $(blrRG)
        AZURE_SUBSCRIPTION_ID: $(25ec632da)
        AZURE_TENANT_ID: $(9c82878)
