variables:
  wd: '$(System.DefaultWorkingDirectory)/integrationTest'

trigger:
  batch: "true"
  branches:
    include:
    - pipeline

# Each provider gets its' own job. These will run in parallel.
# each job gets setup with only the env vars it needs for that run.
# these are defined in azure pipelines web ui as secret variables.

jobs:

- job: Route53
  steps:
  - template: go-env.yaml
  - script: go test -v -verbose -provider ROUTE53
    workingDirectory: $(wd)
    env:
      R53_DOMAIN: $(R53_DOMAIN)
      R53_KEY_ID: $(AKIA6KFGVJVSZKPVDMZL)
      R53_KEY: $(Dj82O9ROz0QD0Nus3Efimv7wvGWKEhrwYZzMtSwF)

- job: Azure
  steps:
    - template: go-env.yaml
    - script: go test -v -verbose -provider AZURE_DNS
      workingDirectory: $(wd)
      env:
        AZURE_CLIENT_ID: $(230323d0-b0c9-4f7a-9f9c-ac87bc393368)
        AZURE_CLIENT_SECRET: $(B1x7Q~iALbe3gJBY-rj3IIbABx6JTTNdEuQRw)
        AZURE_DOMAIN: $(AZ_DOMAIN)
        AZURE_RESOURCE_GROUP: $(blrRG)
        AZURE_SUBSCRIPTION_ID: $(25e09744-4ac8-42ca-8565-4f1a27c632da)
        AZURE_TENANT_ID: $(9c8a3322-d2e5-4737-a68f-a0c4f4902878)
